import test from 'node:test';import assert from 'node:assert/strict';import {createPointerSelection} from '../src/pointerSelection.js';import {startViewerTouch,endViewerTouch} from '../src/viewerGestures.js';
const event=(pointerId=1,clientX=10,clientY=20)=>({pointerId,clientX,clientY,button:0});
test('a cancelled pointer never consumes the next valid tap with the same identifier',()=>{let time=0;const p=createPointerSelection({now:()=>time});p.begin(event(),'old');p.cancel(event());time=600;p.begin(event(),'new');assert.equal(p.end(event()),'new');});
test('movement outside the mesh and window release clear candidates without raycasting',()=>{const p=createPointerSelection();p.begin(event(),'part');const token=p.token(1);p.move(event(1,40));p.finishOutside(event(1,40),token);assert.equal(p.end(event()),null);assert.ok(!p.canApproximate({type:'click',button:0,detail:1}));p.begin(event(),'next');assert.equal(p.end(event()),'next');});
test('deferred outside-release cleanup cannot erase a newer gesture reusing a pointer ID',()=>{const p=createPointerSelection();p.begin(event(),'first');const token=p.token(1);p.end(event());p.begin(event(),'second');p.finishOutside(event(),token);assert.equal(p.end(event()),'second');});
test('even a two-pixel pinch blocks selection until all fingers lift and a fresh tap begins',()=>{const p=createPointerSelection();p.begin(event(1),'one');p.begin({...event(2),isPrimary:false},'two');p.move(event(2,12));assert.equal(p.end(event(2,12)),null);p.move(event(1,12));assert.equal(p.end(event(1,12)),null);assert.ok(!p.canApproximate({type:'click',button:0,detail:1}));p.begin(event(),'fresh');assert.equal(p.end(event()),'fresh');});
test('long presses, right-button misses and double-click notifications are not extra selections',()=>{let t=0;const p=createPointerSelection({now:()=>t});p.begin(event(),'part');t=600;assert.equal(p.end(event()),null);assert.ok(!p.canApproximate({type:'click',button:0,detail:1}));assert.ok(!p.canApproximate({type:'contextmenu',button:2,detail:0}));assert.ok(!p.canApproximate({type:'dblclick',button:0}));assert.ok(p.canApproximate({type:'click',button:0,detail:0}));});
test('blur/hidden/reset cleanup removes every active pointer and pending candidate',()=>{const p=createPointerSelection();p.begin(event(),'part');p.clear();assert.equal(p.token(1),undefined);assert.equal(p.end(event()),null);p.begin(event(),'fresh');assert.equal(p.end(event()),'fresh');});
test('pinch-to-one-finger transitions anchor the remaining finger without stale momentum',()=>{const pinch=startViewerTouch([{clientX:10,clientY:20},{clientX:60,clientY:20}]);assert.equal(pinch.pinch,50);const next=endViewerTouch([{clientX:60,clientY:20}],null);assert.equal(next.release,false);assert.equal(next.pinch,null);assert.deepEqual([next.drag.x,next.drag.startX,next.drag.vOrbit],[60,60,0]);assert.equal(next.interaction,'press');});
test('touch cancellation and extra fingers do not start inertia or leave a dragging appearance',()=>{const drag={active:true,vOrbit:2,vElevation:1};const cancelled=endViewerTouch([],drag,true);assert.equal(cancelled.release,false);assert.equal(cancelled.interaction,'idle');assert.equal(cancelled.drag,null);assert.equal(startViewerTouch([{}, {}, {}]).interaction,'idle');const end=endViewerTouch([],drag);assert.deepEqual(end.orbitVelocity,{azimuth:2,elevation:1});});

test('a new native down recovers a release that happened beyond the browser window',()=>{let t=0;const p=createPointerSelection({now:()=>t});p.down(event());p.begin(event(),'old');t=800;p.down(event());p.begin(event(),'fresh');assert.equal(p.end(event()),'fresh');});
