// Additional labels for the muscle and nervous atlas nodes that are not
// covered by the original curated glossary.
const anatomyGlossaryExtended={
  'pisiform bone':{zh:'豌豆骨'},
  'scaphoid bone':{zh:'舟骨'},
  'second metacarpal bone':{zh:'第二掌骨'},
  'sesamoid bones of foot':{zh:'足部籽骨'},
  'third metacarpal bone':{zh:'第三掌骨'},
  'trapezium bone':{zh:'大多角骨'},
  'trapezoid bone':{zh:'小多角骨'},
  'triquetrum bone':{zh:'三角骨'},
  'abductor digiti minimi of foot':{zh:'小趾展肌（足）'},
  'abductor digiti minimi of hand':{zh:'小指展肌（手）'},
  'abductor hallucis':{zh:'拇展肌'},
  'abductor pollicis brevis':{zh:'拇短展肌'},
  'acromial part of deltoid muscle':{zh:'三角肌肩峰部'},
  'adductor brevis':{zh:'短收肌'},
  'adductor magnus':{zh:'大收肌'},
  'anconeus muscle':{zh:'肘肌'},
  'anterior belly of digastric muscle':{zh:'二腹肌前腹'},
  'brachialis muscle':{zh:'肱肌'},
  'brachioradialis muscle':{zh:'肱桡肌'},
  'clavicular part of deltoid muscle':{zh:'三角肌锁骨部'},
  'coracobrachialis muscle':{zh:'喙肱肌'},
  'extensor carpi radialis brevis':{zh:'桡侧腕短伸肌'},
  'extensor carpi radialis longus':{zh:'桡侧腕长伸肌'},
  'extensor digitorum brevis':{zh:'趾短伸肌'},
  'extensor digitorum longus':{zh:'趾长伸肌'},
  'extensor hallucis longus':{zh:'拇长伸肌'},
  'fibularis brevis muscle':{zh:'腓骨短肌'},
  'fibularis longus muscle':{zh:'腓骨长肌'},
  'fibularis tertius muscle':{zh:'腓骨第三肌'},
  'flexor carpi radialis':{zh:'桡侧腕屈肌'},
  'flexor digitorum brevis':{zh:'趾短屈肌'},
  'flexor digitorum longus':{zh:'趾长屈肌'},
  'flexor digitorum profundus':{zh:'指深屈肌'},
  'flexor hallucis longus':{zh:'拇长屈肌'},
  'frontalis muscle':{zh:'额肌'},
  'gracilis muscle':{zh:'股薄肌'},
  'iliacus muscle':{zh:'髂肌'},
  'infraspinatus muscle':{zh:'冈下肌'},
  'insula subcentral gyrus and ant. and post. sulci':{zh:'岛叶中央下回及前后沟'},
  'insula subcentral gyrus and ant and post sulci':{zh:'岛叶中央下回及前后沟'},
  'lateral head of gastrocnemius':{zh:'腓肠肌外侧头'},
  'lateral head of triceps brachii':{zh:'肱三头肌外侧头'},
  'levator scapulae':{zh:'肩胛提肌'},
  'long head of biceps brachii':{zh:'肱二头肌长头'},
  'long head of biceps femoris':{zh:'股二头肌长头'},
  'long head of triceps brachii':{zh:'肱三头肌长头'},
  'lumbrical muscles of foot':{zh:'蚓状肌（足）'},
  'lumbrical muscles of hand':{zh:'蚓状肌（手）'},
  'medial head of gastrocnemius':{zh:'腓肠肌内侧头'},
  'medial head of triceps brachii':{zh:'肱三头肌内侧头'},
  'mylohyoid muscle':{zh:'下颌舌骨肌'},
  'nasalis muscle':{zh:'鼻肌'},
  'nucleus of solitary tract':{zh:'孤束核'},
  'nucleus of trochlear nerve':{zh:'滑车神经核'},
  'nucleus proprius':{zh:'固有核'},
  'oblique head of adductor hallucis':{zh:'拇收肌斜头'},
  'oblique head of adductor pollicis':{zh:'拇收肌斜头'},
  'oblique part of cricothyroid muscle':{zh:'环甲肌斜部'},
  'obliquus inferior capitis muscle':{zh:'下头斜肌'},
  'obliquus superior capitis muscle':{zh:'上头斜肌'},
  'obturator externus':{zh:'闭孔外肌'},
  'obturator internus':{zh:'闭孔内肌'},
  'occipital pole':{zh:'枕极'},
  'occipitalis muscle':{zh:'枕肌'},
  'occipitotemporal sulcus lateral part':{zh:'枕颞沟外侧部'},
  'olfactory sulcus':{zh:'嗅沟'},
  'omohyoid muscle':{zh:'肩胛舌骨肌'},
  'opercular part of inferior frontal gyrus':{zh:'额下回盖部'},
  'ophthalmic nerve':{zh:'眼神经'},
  'opponens digiti minimi muscle of foot':{zh:'小趾对跖肌'},
  'opponens digiti minimi muscle of hand':{zh:'小指对掌肌'},
  'opponens pollicis muscle':{zh:'拇对掌肌'},
  'optic chiasm':{zh:'视交叉'},
  'optic tract':{zh:'视束'},
  'orbicularis oris muscle':{zh:'口轮匝肌'},
  'orbital gyri':{zh:'眶回'},
  'orbital gyri frontomarginal gyrus and sulcus':{zh:'眶回、额缘回及额缘沟'},
  'orbital part of inferior frontal gyrus':{zh:'额下回眶部'},
  'orbital part of orbicularis oculi':{zh:'眼轮匝肌眶部'},
  'orbital sulci h shaped orbital sulci':{zh:'眶沟H形眶沟'},
  'orbital sulci lateral orbital sulcus':{zh:'眶沟外侧眶沟'},
  'palatopharyngeus muscle':{zh:'腭咽肌'},
  'palmar aponeurosis':{zh:'掌腱膜'},
  'palmar interossei muscles':{zh:'掌骨间肌'},
  'palmaris longus muscle':{zh:'掌长肌'},
  'palpebral part of orbicularis oculi':{zh:'眼轮匝肌睑部'},
  'paracentral gyrus and sulcus':{zh:'中央旁回及中央旁沟'},
  'paracentral sulcus':{zh:'中央旁沟'},
  'parieto occipital sulcus':{zh:'顶枕沟'},
  'patellar ligament':{zh:'髌韧带'},
  'pectineus muscle':{zh:'耻骨肌'},
  'pectoral fascia':{zh:'胸筋膜'},
  'peduncle of flocculus':{zh:'绒球脚'},
  'piriformis fascia':{zh:'梨状肌筋膜'},
  'plantar interossei muscles':{zh:'足底骨间肌'},
  'plantar tendon sheath of fibularis longus muscle':{zh:'腓骨长肌足底腱鞘'},
  'plantaris muscle':{zh:'跖肌'},
  'popliteal fascia':{zh:'腘筋膜'},
  'popliteus muscle':{zh:'腘肌'},
  'postcentral gyrus':{zh:'中央后回'},
  'postcentral sulcus':{zh:'中央后沟'},
  'posterior antebrachial cutaneous nerve':{zh:'前臂后皮神经'},
  'posterior belly of digastric muscle':{zh:'二腹肌后腹'},
  'posterior branch of medial antebrachial cutaneous nerve':{zh:'前臂内侧皮神经后支'},
  'posterior branch of obturator nerve':{zh:'闭孔神经后支'},
  'posterior cochlear nucleus':{zh:'蜗后核'},
  'posterior commissure':{zh:'后连合'},
  'posterior crico arytenoid muscle':{zh:'环杓后肌'},
  'posterior division of inferior trunk of brachial plexus':{zh:'臂丛下干后股'},
  'posterior division of mandibular nerve':{zh:'下颌神经后干'},
  'posterior division of middle trunk of brachial plexus':{zh:'臂丛中干后股'},
  'posterior division of superior trunk of brachial plexus':{zh:'臂丛上干后股'},
  'posterior fasciculus proprius':{zh:'后固有束'},
  'posterior femoral cutaneous nerve':{zh:'股后皮神经'},
  'posterior intermuscular septum of leg':{zh:'小腿后肌间隔'},
  'posterior interosseous nerve of forearm':{zh:'前臂骨间后神经'},
  'posterior layer of thoracolumbar fascia':{zh:'胸腰筋膜后层'},
  'posterior nucleus of vagus nerve':{zh:'迷走神经背侧核'},
  'posterior quadrangular lobule':{zh:'后方小叶'},
  'posterior root of posterior femoral cutaneous nerve':{zh:'股后皮神经后根'},
  'posterior segment of eyeball':{zh:'眼球后段'},
  'posterior spinocerebellar tract':{zh:'脊髓小脑后束'},
  'posterior transverse collateral sulcus':{zh:'后横向侧副沟'},
  'posterolateral tract':{zh:'后外侧束'},
  'precentral gyrus':{zh:'中央前回'},
  'precentral sulcus inferior part':{zh:'中央前沟下部'},
  'precentral sulcus superior part':{zh:'中央前沟上部'},
  'procerus muscle':{zh:'降眉间肌'},
  'pronator quadratus':{zh:'旋前方肌'},
  'pubo analis muscle':{zh:'耻骨肌肛提部'},
  'pubococcygeus muscle':{zh:'耻尾肌'},
  'pudendal nerve':{zh:'阴部神经'},
  'pyramidalis muscle':{zh:'锥状肌'},
  'pyramis of vermis':{zh:'小脑蚓锥体'},
  'quadratus femoris muscle':{zh:'股方肌'},
  'quadratus plantae muscle':{zh:'足底方肌'},
  'radial head of flexor digitorum superficialis':{zh:'指浅屈肌桡侧头'},
  'rectus anterior capitis muscle':{zh:'头前直肌'},
  'rectus femoris muscle':{zh:'股直肌'},
  'rectus lateralis capitis muscle':{zh:'头外侧直肌'},
  'rectus posterior major capitis muscle':{zh:'头后大直肌'},
  'rectus posterior minor capitis muscle':{zh:'头后小直肌'},
  'red nucleus':{zh:'红核'},
  'rhomboid major muscle':{zh:'大菱形肌'},
  'rhomboid minor muscle':{zh:'小菱形肌'},
  'risorius muscle':{zh:'笑肌'},
  'roots of brachial plexus':{zh:'臂丛根'},
  'rotatores':{zh:'回旋肌'},
  'rubrospinal tract':{zh:'红核脊髓束'},
  'sartorius muscle':{zh:'缝匠肌'},
  'scapular spinal part of deltoid muscle':{zh:'三角肌肩胛冈部'},
  'sciatic bursa of gluteus maximus muscle':{zh:'臀大肌坐骨滑囊'},
  'sciatic bursa of obturator internus':{zh:'闭孔内肌坐骨滑囊'},
  'semimembranosus bursa':{zh:'半膜肌滑囊'},
  'semimembranosus muscle':{zh:'半膜肌'},
  'semitendinosus muscle':{zh:'半腱肌'},
  'septal nuclei':{zh:'隔核'},
  'septum pellucidum':{zh:'透明隔'},
  'serratus anterior muscle':{zh:'前锯肌'},
  'short head of biceps brachii':{zh:'肱二头肌短头'},
  'short head of biceps femoris':{zh:'股二头肌短头'},
  'soleus muscle':{zh:'比目鱼肌'},
  'spinal dura':{zh:'脊髓硬膜'},
  'spinal ganglion':{zh:'脊神经节'},
  'spinal reticular process':{zh:'脊髓网状结构'},
  'spinalis capitis muscle':{zh:'棘肌头部'},
  'spinalis colli muscle':{zh:'棘肌颈部'},
  'spinalis thoracis muscle':{zh:'棘肌胸部'},
  'spinotectal tract':{zh:'脊髓顶盖束'},
  'sternocleidomastoid muscle':{zh:'胸锁乳突肌'},
  'sternohyoid muscle':{zh:'胸骨舌骨肌'},
  'sternothyroid muscle':{zh:'胸骨甲状肌'},
  'straight gyrus gyrus rectus':{zh:'直回'},
  'straight part of cricothyroid muscle':{zh:'环甲肌直部'},
  'stria medullaris thalami':{zh:'丘脑髓纹'},
  'stria terminalis':{zh:'终纹'},
  'stylohyoid muscle':{zh:'茎突舌骨肌'},
  'stylopharyngeus muscle':{zh:'茎突咽肌'},
  'subacromial bursa':{zh:'肩峰下滑囊'},
  'subclavian nerve':{zh:'锁骨下神经'},
  'subclavius muscle':{zh:'锁骨下肌'},
  'subcutaneous acromial bursa':{zh:'皮下肩峰滑囊'},
  'subcutaneous bursa of lateral malleolus':{zh:'外踝皮下滑囊'},
  'subcutaneous bursa of medial malleolus':{zh:'内踝皮下滑囊'},
  'subcutaneous bursa of tuberosity of tibia':{zh:'胫骨粗隆皮下滑囊'},
  'subcutaneous calcaneal bursa':{zh:'皮下跟骨滑囊'},
  'subcutaneous infrapatellar bursa':{zh:'髌下皮下滑囊'},
  'subcutaneous prepatellar bursa':{zh:'髌前皮下滑囊'},
  'subcutaneous trochanteric bursa':{zh:'转子皮下滑囊'},
  'subdeltoid bursa':{zh:'三角肌下滑囊'},
  'subfacial prepatellar bursa':{zh:'髌前筋膜下滑囊'},
  'subparietal sulcus':{zh:'顶下沟'},
  'subtendinous bursa of iliacus muscle':{zh:'髂肌腱下滑囊'},
  'subtendinous bursa of infraspinatus muscle':{zh:'冈下肌腱下滑囊'},
  'subtendinous bursa of obturator internus':{zh:'闭孔内肌腱下滑囊'},
  'subtendinous bursa of sartorius muscle':{zh:'缝匠肌腱下滑囊'},
  'subtendinous bursa of teres major muscle':{zh:'大圆肌腱下滑囊'},
  'subtendinous bursa of tibialis anterior':{zh:'胫骨前肌腱下滑囊'},
  'subtendinous bursa of trapezius muscle':{zh:'斜方肌腱下滑囊'},
  'subtendinous bursa of triceps brachii muscle':{zh:'肱三头肌腱下滑囊'},
  'subtendinous calcaneal bursa':{zh:'跟腱下滑囊'},
  'subtendinous prepatellar bursa':{zh:'髌前腱下滑囊'},
  'sulcus interm prim jensen':{zh:'詹森中间沟'},
  'superficial head of flexor pollicis brevis':{zh:'拇短屈肌浅头'},
  'superficial head of pronator teres':{zh:'旋前圆肌浅头'},
  'superficial investing cervical fascia':{zh:'颈深筋膜浅层'},
  'superficial layer of temporal fascia':{zh:'颞筋膜浅层'},
  'superficial part of masseter':{zh:'咬肌浅部'},
  'superficial transverse metacarpal ligament':{zh:'掌骨浅横韧带'},
  'superficial transverse metatarsal ligament':{zh:'跖骨浅横韧带'},
  'superior bursa of biceps femoris muscle':{zh:'股二头肌上滑囊'},
  'superior colliculus':{zh:'上丘'},
  'superior extensor retinaculum of ankle':{zh:'踝伸肌上支持带'},
  'superior fibular retinaculum':{zh:'腓骨上支持带'},
  'superior frontal gyrus':{zh:'额上回'},
  'superior frontal sulcus':{zh:'额上沟'},
  'superior gemellus muscle':{zh:'上孖肌'},
  'superior head of lateral pterygoid muscle':{zh:'翼外肌上头'},
  'superior lateral brachial cutaneous nerve':{zh:'臂外侧上皮神经'},
  'superior oblique muscle':{zh:'上斜肌'},
  'superior occipital gyri':{zh:'枕上回'},
  'superior parietal lobule':{zh:'顶上小叶'},
  'superior pharyngeal constrictor':{zh:'咽上缩肌'},
  'superior rectus muscle':{zh:'上直肌'},
  'superior salivatory nucleus':{zh:'上泌涎核'},
  'superior semilunar lobule':{zh:'上半月小叶'},
  'superior subscapular nerve':{zh:'肩胛下神经上支'},
  'superior tarsus':{zh:'上睑板'},
  'superior temporal gyrus lateral part':{zh:'颞上回外侧部'},
  'superior temporal sulcus':{zh:'颞上沟'},
  'superior trunk of brachial plexus':{zh:'臂丛上干'},
  'supramarginal gyrus':{zh:'缘上回'},
  'suprapatellar bursa':{zh:'髌上滑囊'},
  'supraspinatus muscle':{zh:'冈上肌'},
  'sural nerve':{zh:'腓肠神经'},
  'suspensory ligament of eyeball':{zh:'眼球悬韧带'},
  'synovial sheaths of digits of hand':{zh:'手指滑膜腱鞘'},
  'tectospinal tract':{zh:'顶盖脊髓束'},
  'temporal plane':{zh:'颞平面'},
  'temporal pole':{zh:'颞极'},
  'temporalis muscle':{zh:'颞肌'},
  'temporoparietalis muscle':{zh:'颞顶肌'},
  'tendinous arch of levator ani':{zh:'肛提肌腱弓'},
  'tendon of extensor digitorum longus':{zh:'趾长伸肌腱'},
  'tendon sheath abd. pollicis longus ext. pollicis brevis':{zh:'拇长展肌与拇短伸肌腱鞘'},
  'tendon sheath abd pollicis longus ext pollicis brevis':{zh:'拇长展肌与拇短伸肌腱鞘'},
  'tendon sheath of extensor carpi ulnaris':{zh:'尺侧腕伸肌腱鞘'},
  'tendon sheath of extensor digiti minimi manus':{zh:'小指伸肌腱鞘'},
  'tendon sheath of extensor digitorum and extensor indicis':{zh:'指伸肌与示指伸肌腱鞘'},
  'tendon sheath of extensor digitorum longus':{zh:'趾长伸肌腱鞘'},
  'tendon sheath of extensor hallucis longus':{zh:'拇长伸肌腱鞘'},
  'tendon sheath of extensor pollicis longus':{zh:'拇长伸肌腱鞘'},
  'tendon sheath of extensors carpi radialis':{zh:'桡侧腕伸肌腱鞘'},
  'tendon sheath of flexor carpi radialis':{zh:'桡侧腕屈肌腱鞘'},
  'tendon sheath of flexor digitorum longus':{zh:'趾长屈肌腱鞘'},
  'tendon sheath of flexor hallucis longus':{zh:'拇长屈肌腱鞘'},
  'tendon sheath of flexor pollicis longus':{zh:'拇长屈肌腱鞘'},
  'tendon sheath of tibialis anterior':{zh:'胫骨前肌腱鞘'},
  'tendon sheath of tibialis posterior muscle':{zh:'胫骨后肌腱鞘'},
  'teres minor muscle':{zh:'小圆肌'},
  'thoracodorsal nerve':{zh:'胸背神经'},
  'thyro epiglottic part of thyro arytenoid muscle':{zh:'甲杓肌甲会厌部'},
  'thyrohyoid muscle':{zh:'甲状舌骨肌'},
  'tibialis anterior muscle':{zh:'胫骨前肌'},
  'tibialis posterior muscle':{zh:'胫骨后肌'},
  'tonsil of cerebellum':{zh:'小脑扁桃体'},
  'transversalis fascia':{zh:'腹横筋膜'},
  'transverse arytenoid muscle':{zh:'杓横肌'},
  'transverse frontopolar gyrus and sulcus':{zh:'额极横回及沟'},
  'transverse head of adductor hallucis':{zh:'拇收肌横头'},
  'transverse head of adductor pollicis':{zh:'拇收肌横头'},
  'transverse intermuscular septum of leg':{zh:'小腿横肌间隔'},
  'transverse occipital sulcus':{zh:'枕横沟'},
  'transverse part of trapezius muscle':{zh:'斜方肌横部'},
  'transverse temporal gyri':{zh:'颞横回'},
  'transversus thoracis muscle':{zh:'胸横肌'},
  'triangular part of inferior frontal gyrus':{zh:'额下回三角部'},
  'triceps surae muscle':{zh:'小腿三头肌'},
  'trochanteric bursa of gluteus maximus muscle':{zh:'臀大肌转子滑囊'},
  'trochanteric bursa of gluteus medius muscle':{zh:'臀中肌转子滑囊'},
  'trochanteric bursa of gluteus minimus muscle':{zh:'臀小肌转子滑囊'},
  'trochlea of superior oblique muscle':{zh:'上斜肌滑车'},
  'tuber of vermis':{zh:'小脑蚓结节'},
  'tympanic membrane':{zh:'鼓膜'},
  'ulnar head of extensor carpi ulnaris':{zh:'尺侧腕伸肌尺骨头'},
  'ulnar head of flexor carpi ulnaris':{zh:'尺侧腕屈肌尺骨头'},
  'uvula of vermis':{zh:'小脑蚓垂'},
  'vastus intermedius muscle':{zh:'股中间肌'},
  'vastus lateralis muscle':{zh:'股外侧肌'},
  'vastus medialis muscle':{zh:'股内侧肌'},
  'ventral parts of lateral intertransversarii lumborum muscles':{zh:'腰横突间外侧肌腹侧部'},
  'vestibular nerve':{zh:'前庭神经'},
  'vestibular nuclei':{zh:'前庭神经核'},
  'vitreous body':{zh:'玻璃体'},
  'white matter of telencephalon':{zh:'端脑白质'},
  'wing of central lobule':{zh:'中央小叶翼'},
  'zonular fibres':{zh:'睫状小带纤维'},
  'zygomaticus major muscle':{zh:'颧大肌'},
  'zygomaticus minor muscle':{zh:'颧小肌'}
};
export default anatomyGlossaryExtended;
