import {evidenceFamily,SYSTEMIC_TAGS,hasReportedPain} from './symptomLanguage.js';

const bi=(zh,en)=>({zh,en});
export const BITE_PAIN_CONTEXT=bi('已报告咬东西时痛，应核实牙齿、下颌及可能牵涉的耳、头颈来源；这条信息本身不能证明所选模型结构有局部疼痛。','Pain on biting has been reported. Assess dental/jaw and possible referred ear, head or neck sources; this observation alone does not establish local pain in the selected model structure.');
const SHOULDER_PAIN_CONTEXT=bi('已报告侧躺压肩时疼，应核实实际肩部痛点；这条信息不能证明所选非肩部结构有局部疼痛。','Shoulder pain when lying on that side has been reported. Clarify the actual shoulder pain site; this observation does not establish local pain in the selected non-shoulder structure.');
const dentalThreshold=bi('持续超过2天、咬合痛或牙龈肿胀应看牙医；肿胀影响呼吸、吞咽，立即急诊。','See a dentist for symptoms lasting over 2 days, bite pain or gum swelling. Swelling affecting breathing or swallowing needs emergency care.');
const abdominalThreshold=bi('持续、反复或加重应就医；突然剧痛、出血、腹部僵硬或晕厥立即急诊。','Seek assessment if persistent, recurrent or worsening. Sudden severe pain, bleeding, rigidity or fainting needs emergency care.');
const movementCare=bi('暂减引起不适的负荷，保持舒适范围内的活动；观察动作、休息与症状的关系。','Reduce provoking loads and keep movement within a comfortable range. Observe how activity and rest affect symptoms.');
const movementThreshold=bi('持续加重、明显肿胀或麻木无力应就医；外伤后变形、不能使用或承重，尽快评估。','Seek assessment for worsening symptoms, marked swelling, numbness or weakness. Deformity or inability to use or bear weight after injury needs prompt assessment.');

// These are symptom-level case directions, separate from gated disease rules.
// A single reported feeling can support a broad direction, never a diagnosis
// or an invented second finding. Field order matches the six-field card.
const profiles={
 urinary:{name:bi('排尿相关不适','Urinary-symptom assessment'),shortDescription:bi('排尿疼痛、次数或急迫感变化可有多种原因；单个表现不能确认感染，需要结合伴随变化和检查判断。','Painful urination or changes in frequency or urgency can have several causes. One symptom cannot confirm infection; associated changes and examination help distinguish them.'),triggers:bi('留意排尿前后、饮水与症状变化的关系。','Note how symptoms relate to urination and fluid intake.'),advice:bi('记录起病、排尿和尿液变化，尽快安排评估；不要仅按腰背劳损处理。','Record onset, urination and urine changes, and arrange prompt assessment. Do not assume ordinary back strain.'),threshold:bi('伴发热寒战、血尿或侧腰痛应当日就医；无法排尿或突然剧痛立即急诊。','Fever or chills, blood in urine or flank pain needs same-day assessment. Inability to urinate or sudden severe pain needs emergency care.')},
 flank:{name:bi('侧腰不适：肌骨与尿路方向','Flank discomfort: musculoskeletal and urinary directions'),shortDescription:bi('侧腰痛可来自腰背肌肉、脊柱或泌尿系统等，仅凭位置不能区分。','Flank pain may involve back muscles, the spine or urinary tract, among other causes. Location alone cannot distinguish them.'),triggers:bi('留意动作、姿势、排尿与疼痛的关系。','Note how pain relates to movement, posture and urination.'),advice:bi('确认实际疼痛位置，记录起病和变化；原因不明且持续、反复或加重时及时就医。','Confirm the actual site and record onset and changes. Seek assessment for unexplained pain that persists, recurs or worsens.'),threshold:bi('伴发热寒战、血尿、反复呕吐或排尿变化应尽快就医；剧痛、晕厥或无法排尿立即急诊。','Fever or chills, blood in urine, repeated vomiting or urinary changes needs prompt care. Severe pain, fainting or inability to urinate needs emergency care.')},
 general:{name:bi('局部不适评估方向','Local-discomfort assessment direction'),shortDescription:bi('先分辨实际区域以及疼痛、感觉变化或皮肤表现；单个描述可以提供观察方向，尚不能确定病因。','Distinguish the actual region and pain, sensory or skin changes. One description can guide observation without identifying the cause.'),triggers:bi('留意动作、姿势、接触刺激和症状发生的关系。','Observe the relation to movement, posture, contact irritation and onset.'),advice:bi('确认实际不适区域，选择符合的感觉或表现；持续、加重或影响功能时安排检查。','Confirm the actual area and select matching feelings or signs. Arrange assessment if persistent, worsening or affecting function.'),threshold:bi('突发剧痛、呼吸困难、晕厥或新发无力应立即处理。','Sudden severe pain, breathing difficulty, fainting or new weakness needs immediate care.')},
 systemic:{name:bi('全身表现相关评估','Systemic-symptom assessment'),shortDescription:bi('发热、乏力、口渴或其他全身变化，需结合感染、饮水、睡眠及身体状态区分原因。','Fever, fatigue, thirst or other systemic changes need assessment in relation to infection, hydration, sleep and overall health.'),triggers:bi('感染、作息变化、饮水不足或其他身体问题可能相关。','Infection, sleep changes, low fluid intake or other health problems may be relevant.'),advice:bi('观察体温、饮水排尿及持续时间；持续、反复或影响日常生活时安排检查。','Observe temperature, hydration, urination and duration. Arrange assessment if persistent, recurrent or affecting daily life.'),threshold:bi('明显乏力、持续高热、异常出血、体重下降或反复感染及时就医；气短、晕厥立即处理。','Marked weakness, persistent high fever, abnormal bleeding, weight loss or recurrent infections needs prompt assessment. Breathlessness or fainting needs immediate care.')},
 'dental-load':{
  name:bi('咬合负荷相关牙齿不适','Tooth discomfort related to biting load'),
  shortDescription:bi('牙齿紧绷、酸胀或受压感，可考虑咬紧牙、磨牙或咀嚼负荷；持续单颗牙痛也需检查牙体。','Tight, aching or pressured teeth may relate to clenching, grinding or chewing load. Persistent pain in one tooth also needs a dental check.'),
  triggers:bi('可能与紧张时咬牙、睡眠磨牙或咀嚼硬物有关。','Possible factors include clenching under stress, sleep grinding or chewing hard foods.'),
  advice:bi('留意是否在不自觉咬牙，放松下颌、让上下牙自然分开；暂避硬物，反复发作看牙医。','Notice unconscious clenching, relax the jaw and let teeth rest apart. Avoid hard foods temporarily; see a dentist if recurrent.'),threshold:dentalThreshold,
  sources:['https://www.nidcr.nih.gov/health-info/bruxism','https://www.nhs.uk/symptoms/toothache/']
 },
 tooth:{name:bi('牙齿敏感 / 牙源性疼痛','Tooth sensitivity / dental pain'),shortDescription:bi('可从牙本质敏感、龋齿、牙裂或牙髓刺激方向排查；冷热痛是否持续、是否自发痛有助于区分。','Possible directions include dentine sensitivity, decay, cracks or pulp irritation. Lingering thermal pain and spontaneous pain help distinguish them.'),triggers:bi('冷热、甜食、咬合负荷或牙体损伤。','Temperature, sweet foods, biting load or tooth damage.'),advice:bi('避免反复刺激和用患牙咬硬物，保持温和清洁；留意冷热刺激停止后是否仍痛。','Avoid repeated stimulation or hard biting on the affected tooth. Clean gently and notice whether pain lingers after temperature changes.'),threshold:dentalThreshold},
 'dental-gum':{name:bi('牙龈 / 牙周局部不适','Gum / periodontal discomfort'),shortDescription:bi('牙龈出血、肿胀或牙齿松动，可涉及局部炎症或牙周支持组织问题，需检查具体牙位。','Gum bleeding, swelling or loose teeth may involve local inflammation or tooth-supporting tissues; the affected site needs examination.'),triggers:bi('菌斑、清洁刺激、牙周问题或局部损伤。','Plaque, cleaning irritation, periodontal problems or local injury.'),advice:bi('轻柔刷牙，不挤压肿包；安排口腔检查，确认牙龈和牙周支持情况。','Brush gently and do not squeeze swelling. Arrange a dental examination of the gums and tooth support.'),threshold:dentalThreshold},
 jaw:{name:bi('咀嚼肌 / 颞下颌关节不适','Chewing-muscle / jaw-joint discomfort'),shortDescription:bi('紧绷、咀嚼痛或张口不适可与肌肉负荷和颞下颌关节有关，也要留意是否来自某一颗牙。','Tightness, chewing pain or opening discomfort may involve muscle load or the jaw joint; consider whether pain comes from an individual tooth.'),triggers:bi('咬紧牙、磨牙、嚼硬物或长时间大张口。','Clenching, grinding, hard chewing or prolonged wide opening.'),advice:bi('暂吃软食，减少嚼口香糖和大张口；反复疼痛或张口受限看牙医。','Use softer foods temporarily and reduce gum chewing and wide opening. See a dentist for recurrent pain or limited opening.'),threshold:dentalThreshold},
 eye:{name:bi('眼表刺激 / 眼周不适','Eye-surface irritation / eye-area discomfort'),shortDescription:bi('干涩、异物感或轻度眼周紧绷，可从眼表干燥、刺激与视觉负荷方向观察。','Dryness, grittiness or mild eye-area tightness can suggest surface dryness, irritation or visual strain.'),triggers:bi('长时间看屏幕、干燥环境、隐形眼镜或刺激物。','Prolonged screen use, dry surroundings, contact lenses or irritants.'),advice:bi('暂停连续用眼，规律眨眼、避免揉眼；戴隐形眼镜时不适应先取下。','Take a break from prolonged visual work, blink regularly and avoid rubbing. Remove contact lenses if uncomfortable.'),threshold:bi('视力变化、明显眼痛、畏光或外伤应尽快眼科评估。','Vision changes, significant pain, light sensitivity or injury need prompt eye assessment.')},
 ear:{name:bi('耳部不适 / 牵涉痛','Ear discomfort / referred pain'),shortDescription:bi('耳痛、耳闷或耳鸣需区分耳道、中耳及听觉变化；咀嚼相关痛也可能从牙齿或下颌传来。','Ear pain, fullness or tinnitus can involve the canal, middle ear or hearing; chewing-related pain may refer from teeth or the jaw.'),triggers:bi('进水、挖耳、近期感冒、噪声或咀嚼负荷。','Water, ear picking, a recent cold, noise or chewing load.'),advice:bi('不要往耳内塞物或自行灌洗；持续耳痛、耳闷或耳鸣安排耳鼻喉检查。','Avoid inserting objects or flushing the ear yourself. Arrange an ear examination if pain, fullness or tinnitus persists.'),threshold:bi('突然听力下降当天就医；流液、发热或明显眩晕需及时检查。','Sudden hearing loss needs same-day care. Discharge, fever or marked vertigo needs prompt assessment.')},
 nose:{name:bi('鼻腔刺激 / 鼻窦压力不适','Nasal irritation / sinus-pressure discomfort'),shortDescription:bi('鼻部不适可涉及鼻黏膜刺激、过敏或鼻窦压力；鼻涕特点和持续时间有助于分辨。','Nasal discomfort may involve mucosal irritation, allergy or sinus pressure. Discharge characteristics and duration help distinguish them.'),triggers:bi('粉尘、花粉、干燥空气、感冒或鼻部外伤。','Dust, pollen, dry air, a cold or nasal injury.'),advice:bi('避开明显刺激物，温和清洁鼻部，不反复用力擤鼻；持续或反复症状就医。','Avoid obvious irritants and clean gently without forceful repeated blowing. Seek assessment if persistent or recurrent.'),threshold:bi('眼周肿胀、视力变化、严重头痛或持续鼻出血，尽快就医。','Eye swelling, vision changes, severe headache or persistent nosebleed needs prompt care.')},
 throat:{name:bi('咽喉刺激 / 吞咽相关不适','Throat irritation / swallowing discomfort'),shortDescription:bi('咽部疼痛或紧绷可涉及黏膜刺激、感染、反流或发声负荷，需结合吞咽和声音变化。','Throat pain or tightness can involve irritation, infection, reflux or voice strain; swallowing and voice changes help distinguish them.'),triggers:bi('近期感染、干燥、烟尘、反流或过度发声。','Recent infection, dryness, smoke, reflux or heavy voice use.'),advice:bi('减少烟尘与过度发声，能吞咽时少量饮水；持续或加重安排检查。','Reduce smoke and voice strain; sip fluids if able to swallow. Arrange assessment if persistent or worsening.'),threshold:bi('呼吸困难、无法吞咽液体、流口水或迅速肿胀，立即就医。','Breathing difficulty, inability to swallow liquids, drooling or rapid swelling needs immediate care.')},
 head:{name:bi('头痛 / 头面部紧张不适','Headache / head and facial tension'),shortDescription:bi('头痛或头面紧绷可涉及肌肉紧张、睡眠不足或其他头痛类型；起病方式及伴随变化很重要。','Head pain or tightness may involve muscle tension, poor sleep or other headache patterns; onset and associated changes matter.'),triggers:bi('压力、睡眠变化、缺水、持续用眼或颈部姿势。','Stress, sleep changes, low fluid intake, prolonged visual work or neck posture.'),advice:bi('休息，保持正常饮水与作息，观察持续时间；新发、反复或加重头痛安排评估。','Rest and maintain normal hydration and sleep. Observe duration; arrange assessment for new, recurrent or worsening headaches.'),threshold:bi('突发最严重头痛、意识或说话变化、单侧无力立即急诊；发热颈硬及时就医。','Sudden worst headache, altered awareness or speech, or one-sided weakness needs emergency care. Fever with a stiff neck needs urgent assessment.')},
 chest:{name:bi('胸部不适：胸壁与心肺方向','Chest discomfort: chest-wall and cardiopulmonary directions'),shortDescription:bi('胸部痛、紧绷或受压感需要分辨胸壁、心肺及食管来源；不能仅凭点位或压痛排除心肺问题。','Chest pain, tightness or pressure can originate in the chest wall, heart, lungs or oesophagus; location or tenderness cannot exclude heart or lung causes.'),triggers:bi('活动负荷、深呼吸、咳嗽、进食或胸壁动作可能相关。','Exertion, breathing, coughing, meals or chest-wall movement may be relevant.'),advice:bi('停止引起不适的活动；新发或原因不明的胸部症状尽快评估，记录持续时间和伴随变化。','Stop provoking activity. Seek prompt assessment for new or unexplained chest symptoms, noting duration and associated changes.'),threshold:bi('压迫感持续不缓解，或伴气短、冷汗、晕厥、向手臂下颌放射，立即急诊。','Persistent pressure or symptoms with breathlessness, cold sweat, fainting or arm/jaw radiation need emergency care.')},
 abdomen:{name:bi('腹部不适：腹壁与消化方向','Abdominal discomfort: wall and digestive directions'),shortDescription:bi('腹部不适可来自腹壁负荷、肠气或消化问题；侧腰痛与排尿变化也可能涉及尿路。','Abdominal discomfort can involve wall strain, gas or digestive problems. Flank pain with urinary changes may involve the urinary tract.'),triggers:bi('运动牵拉、进食、排便、排尿或月经时间可能相关。','Movement, meals, bowel movements, urination or the menstrual cycle may be relevant.'),advice:bi('观察实际左右上下位置及与进食、动作、排便的关系；持续、反复或加重安排评估。','Observe the actual quadrant and relation to meals, movement and bowel movements. Arrange assessment if persistent, recurrent or worsening.'),threshold:abdominalThreshold},
 pelvis:{name:bi('盆腔 / 会阴不适','Pelvic / perineal discomfort'),shortDescription:bi('该区域不适可涉及盆底肌、尿路、生殖系统或肠道，排尿、排便及月经变化有助区分。','This discomfort may involve pelvic muscles, urinary, reproductive or bowel systems; urinary, bowel and menstrual changes help distinguish it.'),triggers:bi('久坐、肌肉用力、排尿排便、月经或局部刺激。','Sitting, muscle strain, urination, bowel movements, menstruation or local irritation.'),advice:bi('暂减局部负荷，注意排尿、排便与出血变化；持续或反复症状安排检查。','Reduce local load temporarily and watch urinary, bowel and bleeding changes. Arrange assessment if persistent or recurrent.'),threshold:bi('剧痛、排尿困难、发热、明显出血，或可能怀孕且疼痛，应尽快就医。','Severe pain, difficulty urinating, fever, significant bleeding or pain with possible pregnancy needs prompt care.')},
 sensory:{name:bi('感觉异常 / 神经刺激方向','Altered sensation / nerve-irritation direction'),shortDescription:bi('麻木、麻刺或电击感可与局部神经刺激或受压有关；分布范围和是否无力比疼痛词本身更有帮助。','Numbness, tingling or electric sensations may involve nerve irritation or pressure. Distribution and weakness help more than the pain word alone.'),triggers:bi('持续压迫、固定姿势、反复动作或局部损伤。','Prolonged pressure, fixed posture, repeated movement or local injury.'),advice:bi('解除明显压迫，温和变换姿势；持续、扩散或反复出现时评估神经功能。','Remove obvious pressure and change position gently. Seek a nerve-function assessment if persistent, spreading or recurrent.'),threshold:bi('突然单侧无力、说话变化立即急救；进行性无力、会阴麻木或排尿困难立即就医。','Sudden one-sided weakness or speech changes need emergency care. Progressive weakness, saddle numbness or urinary difficulty needs immediate assessment.')},
 skin:{name:bi('局部皮肤刺激 / 炎症方向','Local skin irritation / inflammation direction'),shortDescription:bi('痒、红斑或皮疹可涉及表面刺激、过敏或炎症；应看皮肤变化，不能从下方骨肌模型判断皮肤病名。','Itch, redness or rash may involve irritation, allergy or inflammation. Visible skin changes guide assessment, rather than the underlying bone or muscle.'),triggers:bi('摩擦、汗液、接触物、虫咬或皮肤损伤。','Friction, sweat, contact substances, bites or skin injury.'),advice:bi('停用可疑接触物，温和清洁，不抓挠或挤破；反复、扩散或渗液时就医。','Stop suspected contact products, clean gently and avoid scratching or squeezing. Seek assessment if recurrent, spreading or weeping.'),threshold:bi('迅速扩散、明显红热疼痛伴发热，及时就医；面唇肿胀伴呼吸困难立即急救。','Rapid spread or hot painful redness with fever needs prompt care. Facial/lip swelling with breathing difficulty is an emergency.')},
 fatigue:{name:bi('疲劳 / 恢复不足方向','Fatigue / insufficient recovery direction'),shortDescription:bi('乏力或困倦可与睡眠和恢复不足有关，也可能涉及感染、贫血等；单个感觉不能分清原因。','Fatigue or sleepiness may involve insufficient sleep or recovery, infection or anaemia; one feeling cannot separate the causes.'),triggers:bi('作息变化、连续劳累、压力、进食饮水不足或身体疾病。','Sleep changes, prolonged exertion, stress, low food/fluid intake or illness.'),advice:bi('规律作息与饮食饮水，暂减过度负荷；持续乏力、影响日常生活或反复出现安排检查。','Maintain regular sleep, meals and fluids and reduce excessive load. Seek assessment if persistent, recurrent or affecting daily life.'),threshold:bi('伴胸痛、气短、晕厥需及时处理；异常出血、体重下降或反复感染尽快检查。','Chest pain, breathlessness or fainting needs prompt care. Abnormal bleeding, weight loss or recurrent infections needs assessment.')}
};

const organDescriptions={
 oesophagus:bi('食管区域不适可涉及反流或吞咽相关问题，需分辨与进食、平躺、吞咽的关系。','Oesophageal-area discomfort may involve reflux or swallowing problems; relation to meals, lying down and swallowing helps distinguish them.'),
 stomach:bi('胃区不适可从消化不良、胃酸刺激或胃肠功能变化方向观察；餐后饱胀和反酸有助区分。','Stomach-area discomfort can involve indigestion, acid irritation or digestive changes. Meal-related fullness and reflux help distinguish them.'),
 intestine:bi('肠区不适可涉及肠气、肠道感染或排便功能变化，腹泻、呕吐与排便后变化有助区分。','Intestinal-area discomfort may involve gas, infection or bowel-function changes. Diarrhoea, vomiting and changes after bowel movements help distinguish them.'),
 colon:bi('结肠区域不适可涉及肠气、便秘、肠道炎症或功能性变化，需看排便特点与持续时间。','Colon-area discomfort may involve gas, constipation, inflammation or functional changes; bowel characteristics and duration help distinguish them.'),
 appendix:bi('右下腹不适需考虑肠道、尿路及阑尾等来源；痛迁移、持续加重或发热时应尽快排查。','Right-lower discomfort can involve bowel, urinary or appendix causes. Migrating pain, worsening pain or fever needs prompt assessment.'),
 liver:bi('右上腹不适可能涉及肝胆、消化道或腹壁；黄疸、尿色与进食相关性有助区分。','Right-upper discomfort may involve liver/biliary, digestive or abdominal-wall causes. Jaundice, urine colour and meal association help distinguish them.'),
 biliary:bi('右上腹不适可涉及胆囊胆道，也可能来自胃肠或腹壁；油腻餐后发作、持续痛和发热需关注。','Right-upper discomfort can involve the gallbladder/bile ducts, gut or abdominal wall. Fatty-meal episodes, persistent pain and fever matter.'),
 pancreas:bi('上腹不适可能来自胃、胆道或胰腺等；持续明显疼痛、向背部放射或呕吐需及时评估。','Upper abdominal discomfort may involve the stomach, biliary tract or pancreas. Persistent significant pain, back radiation or vomiting needs prompt assessment.'),
 spleen:bi('左上腹不适可涉及胃肠、腹壁或脾区；近期碰撞或外伤会改变处理优先级。','Left-upper discomfort can involve the gut, abdominal wall or spleen area. Recent impact or injury changes the urgency.'),
 kidney:bi('侧腰不适可涉及腰背肌肉或肾脏尿路；尿痛、血尿、发热或向腹股沟放射有助区分。','Flank discomfort may involve back muscles or kidneys/urinary tract. Painful urination, blood in urine, fever or groin radiation helps distinguish them.'),
 ureter:bi('腰腹到腹股沟的不适可涉及输尿管，也可能是肌肉或肠道来源；尿痛、血尿和绞痛是区分线索。','Flank-to-groin discomfort may involve the ureter, muscles or bowel. Painful urination, blood in urine and colic help distinguish them.'),
 bladder:bi('下腹不适可涉及膀胱尿路、盆底或肠道；尿频、尿急、尿痛与排尿变化有助区分。','Lower-abdominal discomfort can involve bladder/urinary, pelvic-floor or bowel causes. Frequency, urgency, painful urination and urinary changes help distinguish them.')
};
const movementDirections={neck:['颈部姿势 / 肌肉负荷不适','Neck posture / muscle-load discomfort'],spine:['腰背机械性 / 姿势相关不适','Mechanical / posture-related back discomfort'],shoulder:['肩部肌腱 / 关节负荷不适','Shoulder tendon / joint-load discomfort'],'upper-limb':['上肢肌腱 / 关节负荷不适','Upper-limb tendon / joint-load discomfort'],hand:['手腕与手指负荷不适','Wrist and finger load discomfort'],hip:['髋臀肌肉 / 关节负荷不适','Hip and buttock muscle / joint-load discomfort'],knee:['膝部负荷 / 关节不适','Knee-load / joint discomfort'],ankle:['踝部软组织 / 关节不适','Ankle soft-tissue / joint discomfort'],foot:['足部负荷 / 局部刺激不适','Foot-load / local-irritation discomfort'],'lower-limb':['下肢肌肉 / 骨关节负荷不适','Lower-limb muscle / bone and joint-load discomfort']};
const hasAny=(tags,ids)=>ids.some(id=>tags.has(id));

export function basicAssessment(profile,report,urgent=[],knowledge){
 const tags=report.tags;
 if(!tags.size)return null;
 const timeOnly=new Set(['刚刚开始','持续数小时','持续1至3天','持续超过3天','持续加重','反复数月','短暂发作','突然起病','持续超过10天','经期相关','可能怀孕']);
 if([...tags].every(t=>timeOnly.has(t)))return null;
 const nonOralBiting=tags.has('咬合痛')&&!['tooth','jaw'].includes(profile.region);
 const remoteShoulder=tags.has('侧卧肩痛')&&profile.region!=='shoulder';
 const routingTags=[...tags].filter(tag=>(!nonOralBiting||tag!=='咬合痛')&&(!remoteShoulder||tag!=='侧卧肩痛'));
 // Preserve only one real selected observation per family, with symptoms
 // before timing/triggers. A broad card is visibly marked as basic.
 const evidence=new Map();for(const tag of tags)if(!evidence.has(evidenceFamily(tag)))evidence.set(evidenceFamily(tag),tag);
 let why=[...evidence.values()].slice(0,3);
 let key=profile.region,content;
 if(urgent.length){
  key='priority';content={name:bi(`${profile.title.zh}需优先评估`,`${profile.title.en}: priority assessment`),shortDescription:bi('当前信号需要先接受相应评估，再考虑一般疼痛或生活方式解释。','The reported signal needs the indicated assessment before routine pain or lifestyle interpretation.'),triggers:bi('需要结合起病、外伤和伴随变化检查，不先归因于劳累或紧张。','Assess onset, injury and associated changes before attributing symptoms to exertion or stress.'),advice:urgent[0],threshold:bi('按上方优先处理提示行动，无需等待勾选更多表现。','Follow the priority guidance above without waiting to select more findings.')};
 }else if(profile.region==='nose'&&tags.has('鼻出血')){key='nosebleed';content={...profiles.nose,name:bi('鼻出血相关评估','Nosebleed assessment'),shortDescription:bi('鼻出血可有多种原因，需分辨当前是否仍出血、是否反复，以及外伤或其他变化。','Nosebleeding has several possible causes. Clarify whether it is ongoing or recurrent and whether injury or other changes are present.'),advice:bi('若正在流鼻血，坐直前倾，捏住鼻子柔软部位持续10–15分钟，用口呼吸，不仰头。','If bleeding now, sit upright and lean forward, pinch the soft part continuously for 10–15 minutes and breathe through the mouth. Do not tilt the head back.'),threshold:bi('正确按压10–15分钟仍未止，或出血量大、气短、明显头晕/无力，立即急诊；反复发作请就医。','Bleeding persisting after 10–15 minutes of firm pressure, heavy bleeding, breathlessness or marked dizziness/weakness needs emergency care. Recurrent episodes need medical review.')};
 }else if(['abdomen','pelvis','spine','hip'].includes(profile.region)&&hasAny(tags,['尿痛','尿频','尿急'])){key='urinary';content=profiles[key];
 }else if(['abdomen','spine','hip'].includes(profile.region)&&tags.has('侧腰痛')){key='flank';content=profiles[key];
 }else if(hasAny(tags,['牙龈出血','牙龈肿胀','牙齿松动','牙龈退缩'])&&['tooth','jaw'].includes(profile.region)){key='dental-gum';content=profiles[key];
 }else if(profile.region==='tooth'&&hasAny(tags,['紧绷','酸胀','压迫感','磨牙'])){key='dental-load';content=profiles[key];
 }else if(hasAny(tags,['痒','灼痒','皮疹','红斑','水泡','脱皮','渗液','破皮'])){key='skin';content=profiles[key];
 }else if(hasAny(tags,['麻木','麻刺','感觉减退','电击','拇食中指麻木','无名小指麻木','夜间麻木','屈肘加重','面部麻木'])){
  key='sensory';content=profiles[key];
  if(tags.has('面部麻木'))content={...content,
   shortDescription:bi('已报告面部麻木，需要核实起病、持续时间和实际分布；模型侧别不能确认症状侧别，也不能确定神经受压或其他病因。','Facial numbness has been reported. Clarify its onset, duration and actual distribution; the model side does not establish the symptom side, nerve compression or another cause.'),
   triggers:bi('记录感觉变化的起病、持续或反复情况，以及同时出现的其他变化。','Record how the sensory change began, whether it persists or recurs, and any accompanying changes.'),
   advice:bi('记录实际麻木范围和变化；原因不明且持续、扩散或反复时安排医疗评估，不先按头痛、紧张或局部受压处理。','Record the actual numb area and changes. Arrange medical assessment for unexplained persistent, spreading or recurrent symptoms rather than assuming headache, tension or local compression.'),
   threshold:bi('若面部麻木突然出现，或伴面部歪斜、说话变化或突然无力，立即联系急救并记录起病时间。','If facial numbness begins suddenly, or accompanies facial droop, speech changes or sudden weakness, call emergency services and note the onset time.')};
 }else if(routingTags.length&&!routingTags.every(t=>timeOnly.has(t))&&routingTags.every(t=>SYSTEMIC_TAGS.has(t))){key=routingTags.every(t=>['疲劳乏力','白天困倦','睡眠不足','失眠'].includes(t))?'fatigue':'systemic';content=profiles[key];
 }else if(nonOralBiting&&!hasReportedPain(tags)&&![...tags].some(tag=>tag!=='咬合痛'&&!timeOnly.has(tag)&&['feelings','signs'].some(field=>knowledge?.[field]?.some(option=>option.id===tag)))){
  content={...profiles.general,name:bi('咬合痛：需核实实际部位','Pain on biting: confirm the actual area'),shortDescription:BITE_PAIN_CONTEXT,triggers:bi('留意咬合、咀嚼与实际痛点及其他变化的关系。','Note the relation of biting and chewing to the actual pain site and other changes.'),advice:bi('安排牙科或医疗检查，说明实际痛点和咬合诱因，并一起说明其他已选变化。','Arrange dental or medical assessment, describe the actual site and biting trigger, and mention other reported changes.'),threshold:bi('伴发热或寒战应当天评估；呼吸或吞咽困难、迅速加重的肿胀应立即就医。','Fever or chills need same-day assessment. Breathing or swallowing difficulty or rapidly worsening swelling needs immediate care.')};
 }else if(remoteShoulder&&!hasReportedPain(tags)&&!routingTags.some(tag=>!timeOnly.has(tag)&&['feelings','signs'].some(field=>knowledge?.[field]?.some(option=>option.id===tag)))){
  content={...profiles.general,name:bi('肩部受压疼痛：需核实实际部位','Shoulder pressure pain: confirm the actual area'),shortDescription:SHOULDER_PAIN_CONTEXT};
 }else if(['neck','spine'].includes(key)&&hasAny(tags,['外伤后','扭伤后'])&&hasReportedPain(tags)){
  content={name:bi('受伤后的颈背不适','Neck/back discomfort after injury'),shortDescription:bi('受伤后的颈背疼痛需要结合受伤经过和功能变化判断，不能仅按姿势或肌肉紧张解释。','Neck/back pain after injury needs assessment of the mechanism and functional changes rather than a posture-only explanation.'),triggers:bi('核实碰撞或扭转的经过、起病及活动能力；当前信息不能确认受损组织。','Clarify the impact or twisting mechanism, onset and function; the affected tissue is not established.'),advice:bi('先保护受伤部位，避免加重动作或强行拉伸；疼痛持续、反复或影响功能时及时就医评估。','Protect the injured area and avoid provoking movements or forced stretching. Arrange assessment for persistent, recurrent or function-limiting pain.'),threshold:bi('明显外伤、剧痛、麻木无力或不能正常活动需尽快评估；新发排尿困难、会阴麻木或突然力量下降立即急诊。','Significant trauma, severe pain, numbness, weakness or inability to move normally needs urgent assessment. New difficulty urinating, saddle numbness or sudden strength loss needs emergency care.')};
 }else if(movementDirections[key]){
  content={name:bi(...movementDirections[key]),shortDescription:bi('局部痛、紧绷或活动不适，可从软组织负荷和关节方向观察；有外伤、骨点压痛时也需排查骨损伤。','Local pain, tightness or movement discomfort can involve soft-tissue load or joints. Injury with focal bone tenderness also needs assessment for bone damage.'),triggers:bi('固定姿势、反复用力、运动负荷或扭伤碰撞可能相关。','Fixed posture, repeated strain, exercise load or twisting/impact may be relevant.'),advice:movementCare,threshold:movementThreshold};
 }else{content=profiles[key]||profiles.general;}
 // Biting is retained as a reported observation/context, never the local-pain
 // representative of a non-dental basic card. The dedicated bite direction
 // and its own priority action may still show that actual observation as why.
 if(nonOralBiting&&content.shortDescription!==BITE_PAIN_CONTEXT&&!(key==='priority'&&urgent[0]?.id==='biting-pain-fever-review')){
  const localEvidence=new Map();for(const tag of tags)if(tag!=='咬合痛'&&!localEvidence.has(evidenceFamily(tag)))localEvidence.set(evidenceFamily(tag),tag);
  why=[...localEvidence.values()].slice(0,3);
 }
 // Keep the observation that actually selected this broad direction visible.
 if(['urinary','flank'].includes(key)){
  const anchors=key==='urinary'?['尿痛','尿频','尿急']:['侧腰痛'];
  const ordered=new Map();
  for(const tag of [...anchors.filter(tag=>tags.has(tag)),...tags])if((!nonOralBiting||tag!=='咬合痛')&&!ordered.has(evidenceFamily(tag)))ordered.set(evidenceFamily(tag),tag);
  why=[...ordered.values()].slice(0,3);
 }
 if(!urgent.length&&content.shortDescription!==BITE_PAIN_CONTEXT&&content.shortDescription!==SHOULDER_PAIN_CONTEXT&&!['fatigue','systemic','sensory','skin','urinary','flank'].includes(key)&&profile.organ&&organDescriptions[profile.organ])content={...profiles.abdomen,name:bi(`${profile.label.zh}区域不适方向`,`${profile.label.en} area discomfort`),shortDescription:organDescriptions[profile.organ]};
 if(remoteShoulder&&content.shortDescription!==SHOULDER_PAIN_CONTEXT){
  why=why.filter(tag=>tag!=='侧卧肩痛');
  content={...content,shortDescription:bi(`${content.shortDescription.zh} ${SHOULDER_PAIN_CONTEXT.zh}`,`${content.shortDescription.en} ${SHOULDER_PAIN_CONTEXT.en}`)};
 }
 // The organ-specific wording must never replace urgency or a selected
 // systemic/sensory/skin direction.
 return {...content,id:`basic-${key}-${profile.organ||profile.region}`,basic:true,why,evidenceFamilies:why.map(evidenceFamily),matchedSymptoms:[...tags],partRefs:[{part:report.part,layer:report.layer}]};
}
