// Every active branch has an explicit evidence gate. Groups are alternatives
// within a feature, AND across features. Missing input is unknown, not absent.
// These are assessment directions; scores are ranks, never probabilities.
const P=['疼痛','针刺','钝痛','胀痛','酸痛','灼烧','跳痛','撕裂','电击','抽筋','压迫感','隐痛','刺痛','刀割感','牵拉痛','酸胀','紧绷','紧箍感','酸涩','咬合痛','呼吸痛','绞痛'];
const limb=['neck','spine','shoulder','upper-limb','hand','chest','abdomen','pelvis','hip','knee','lower-limb','ankle','foot'];
const joints=['shoulder','upper-limb','hand','hip','knee','ankle','foot'];
const neural=['neck','spine','shoulder','upper-limb','hand','hip','lower-limb','ankle','foot'];
const ALL=['head','eye','ear','nose','tooth','jaw','throat',...limb,'autonomic'];
const r=(regions,family,required,options={})=>({regions,family,required,optional:[],...options});
export const CLINICAL_RULES={
 'muscle-strain':r(limb,'mechanical',[P,['运动后','反复用力','外伤后','活动诱发']],{tissues:['muscle'],exclude:['新运动后1至3天']}),
 'nerve-irritation':r(neural,'neural',[['麻木','麻刺','感觉减退'],['电击','灼烧','放射痛','肌力下降']],{priority:0}),
 'skin-irritation':r(ALL,'skin',[['皮疹','红斑','脱皮','水泡','干燥'],['灼烧','刺痛','痒','灼痒']],{exclude:['流脓']}),
 'joint-inflammation':r(joints,'joint',[['红肿','局部肿胀'],['局部发热','活动受限',...P]],{optional:['晨起僵硬']}),
 'itch-skin-pattern':r(ALL,'skin',[['痒','灼痒'],['皮疹','红斑','水泡','起包']],{exclude:['流脓'],priority:2}),
 'minor-injury-bruise':r(limb,'injury',[['外伤后'],['淤青','局部肿胀',...P]]),
 'muscle-cramp-pattern':r(limb,'cramp',[['抽筋'],['短暂发作','运动后','久站后']],{tissues:['muscle']}),
 'head-pressure-pattern':r(['head'],'headache',[['紧箍感','压迫感'],['双侧头痛','压力大','睡眠不足']],{exclude:['突发最严重头痛','突然单侧无力','呕吐']}),
 'dental-pulpitis':r(['tooth','jaw'],'pulp',[['持续冷热痛','自发痛','夜间痛'],['持续冷热痛','自发痛','夜间痛','放射痛']],{optional:['放射痛'],priority:4}),
 'rhinosinusitis':r(['nose'],'nasal',[['鼻塞'],['脓性鼻涕','面部压胀']],{optional:['持续超过10天','发热']}),
 'nasal-trauma-epistaxis':r(['nose'],'nasal-injury',[['外伤后'],['鼻出血','淤青',...P]]),
 'vertebral-mechanical-pain':r(['neck','spine'],'mechanical',[P,['活动诱发','久坐后','反复用力']],{exclude:['外伤后','扭伤后'],priority:1}),
 'spinal-radiculopathy':r(neural,'neural',[['放射痛'],['麻木','麻刺','感觉减退','肌力下降']],{priority:3}),
 'rib-wall-injury':r(['chest'],'injury',[['外伤后'],['呼吸痛','局部压痛','淤青']],{priority:3}),
 'rotator-cuff-irritation':r(['shoulder'],'shoulder-load',[P,['抬臂加重','侧卧肩痛']],{optional:['肌力下降','反复用力']}),
 'ulnar-nerve-irritation':r(['upper-limb','hand'],'neural',[['无名小指麻木'],['屈肘加重','夜间麻木','肌力下降']],{priority:5}),
 'ankle-sprain':r(['ankle'],'injury',[['扭伤后'],['局部肿胀','淤青','活动受限',...P]],{priority:3}),
 'foot-plantar-pain':r(['foot','ankle'],'heel',[P,['晨起第一步痛']],{optional:['久站后']}),
 'cranial-nerve-pattern':r(['head','eye','ear','jaw','throat'],'cranial',[['感觉减退','面部麻木'],['肌力下降','复视','吞咽困难']]),
 'spinal-cord-warning':r(['neck','spine','hip','lower-limb'],'cord',[['会阴麻木','排尿困难'],['肌力下降','感觉减退','麻木','放射痛']],{priority:6}),
 'abdominal-wall-strain':r(['abdomen'],'mechanical',[P,['转身牵拉痛','运动后']],{tissues:['muscle'],exclude:['发热','腹泻','呕吐','血便'],priority:3}),
 'neck-muscle-tension':r(['neck'],'mechanical',[P,['久坐后','压力大','转头加重']],{tissues:['muscle'],exclude:['外伤后','扭伤后'],priority:3}),
 'thoracolumbar-myofascial':r(['spine'],'mechanical',[P,['久坐后','反复用力','活动诱发']],{tissues:['muscle'],exclude:['外伤后','扭伤后'],priority:3}),
 'dental-caries':r(['tooth'],'tooth-lesion',[['牙龋洞'],['冷热敏感','咬合痛',...P]],{priority:2}),
 'gingivitis-periodontitis':r(['tooth','jaw'],'gum',[['牙龈出血'],['牙龈肿胀','口腔异味']],{priority:1}),
 'tmj-dysfunction':r(['jaw'],'jaw',[['咬合痛','咀嚼加重'],['张口受限','关节卡住','张口弹响']],{optional:['磨牙']}),
 'dental-fracture':r(['tooth'],'tooth-lesion',[['牙齿裂纹','外伤后'],['咬合痛','冷热敏感']],{priority:3}),
 'migraine-pattern':r(['head'],'headache',[['跳痛','单侧头痛'],['畏光','恶心','呕吐']],{optional:['活动诱发'],priority:3}),
 'trigeminal-neuralgia':r(['head','jaw','tooth'],'facial-neuralgia',[['电击','刀割感'],['触碰诱发'],['短暂发作']],{priority:4}),
 'carpal-tunnel':r(['hand','upper-limb'],'neural',[['拇食中指麻木'],['夜间麻木','甩手缓解','肌力下降']],{priority:5}),
 'sciatic-neuralgia':r(['spine','hip','lower-limb','foot'],'neural',[['放射痛'],['沿腿向下'],['麻木','麻刺','感觉减退','肌力下降']],{priority:4}),
 'peripheral-neuropathy':r(['hand','lower-limb','foot'],'neural',[['麻木','麻刺','灼烧','感觉减退'],['双侧手足对称']],{priority:3}),
 'facial-nerve-palsy':r(['head','eye','jaw'],'cranial',[['面部歪斜'],['闭眼困难']],{priority:4}),
 'tendon-overuse':r(joints,'tendon',[P,['反复用力'],['活动诱发','局部压痛']],{optional:['局部肿胀']}),
 'bursitis-pattern':r(['shoulder','hip','knee','ankle'],'joint',[['局部肿胀'],['局部压痛','侧卧肩痛','跪地加重']],{optional:['反复用力'],priority:1}),
 'knee-meniscus-ligament':r(['knee'],'injury',[['扭伤后'],['关节卡住','关节不稳','无法承重']],{optional:['局部肿胀'],priority:4}),
 'gastroenteritis-pattern':r(['abdomen'],'bowel-acute',[['腹泻'],['呕吐','恶心','绞痛','发热']],{exclude:['反复数月']}),
 'appendicitis-pattern':r(['abdomen'],'appendix',[P,['腹痛迁移至右下腹','持续加重']],{locations:['rlq'],optional:['发热','恶心','呕吐'],priority:4}),
 'renal-colic-pattern':r(['abdomen','spine','hip'],'urinary-stone',[['绞痛','腰腹向腹股沟放射'],['血尿','腰腹向腹股沟放射']],{locations:['flank'],priority:4}),
 'pleuritic-chest-pain':r(['chest'],'respiratory',[['呼吸痛'],['咳嗽','气短','发热']],{priority:2}),
 'eye-surface-irritation':r(['eye'],'eye-surface',[['眼干','异物感','酸涩','灼烧'],['流泪','眼红']],{exclude:['视物模糊','畏光','外伤后']}),
 'ear-infection-pattern':r(['ear'],'ear',[P,['耳道流液','听力下降','发热']],{optional:['耳屏牵拉痛']}),
 'gout-like-arthritis':r(['hand','knee','ankle','foot'],'joint',[['红肿','局部肿胀'],['局部发热'],['突然起病']],{optional:['活动受限'],priority:3}),
 'deep-vein-thrombosis-warning':r(['lower-limb'],'vascular',[['单侧肿胀'],[...P,'局部发热','红肿']],{priority:6}),
 'diverticular-left-abdominal':r(['abdomen'],'bowel-left',[P,['发热','排便改变','血便']],{locations:['llq'],priority:3}),
 'biliary-colic-pattern':r(['abdomen'],'biliary',[P,['油腻餐后痛','黄疸']],{locations:['ruq','epigastric'],optional:['呕吐','发热'],priority:3}),
 'urinary-tract-infection-pattern':r(['abdomen','pelvis','spine','hip'],'lower-urinary',[['尿痛'],['尿频','尿急']],{optional:['血尿'],priority:2}),
 'reflux-dyspepsia-pattern':r(['abdomen','chest'],'reflux',[['反酸'],['灼烧','进食后加重','躺下加重']],{locations:['epigastric','luq'],locationRegions:['abdomen'],exclude:['吞咽困难']}),
 'dental-abscess':r(['tooth','jaw'],'dental-infection',[['牙龈肿胀','面部肿胀','流脓'],['发热','咬合痛',...P]],{optional:['口腔异味'],priority:5}),
 'pharyngitis':r(['throat'],'throat',[['吞咽痛'],['发热','咳嗽','咽部红肿']],{exclude:['呼吸困难']}),
 'pelvic-pain':r(['pelvis','abdomen'],'pelvic',[P,['经期相关','异常分泌物','可能怀孕']],{locations:['suprapubic','llq','rlq']}),
 'bone-injury':r(limb,'injury',[['外伤后'],['无法承重','局部压痛','局部肿胀']],{tissues:['skeleton'],priority:3}),
 'autonomic-assessment':r(['autonomic'],'autonomic',[['心悸','眩晕'],['出汗','体位改变诱发']],{priority:0}),
 'cardiac-ischaemia-warning':r(['chest'],'cardiac',[['压迫感','灼烧','放射痛'],['气短','静息气短','冷汗','晕厥','恶心','运动诱发胸闷']],{priority:6}),
 'pancreatitis-pattern':r(['abdomen'],'pancreas',[P,['向背部放射'],['呕吐','持续加重']],{locations:['epigastric','luq'],priority:4}),
 'hepatobiliary-pattern':r(['abdomen'],'liver',[['黄疸'],['尿色深','苍白便','疲劳乏力',...P]],{priority:3}),
 'splenic-injury-warning':r(['abdomen'],'splenic',[['外伤后'],['肩尖痛','局部压痛',...P]],{locations:['luq'],priority:5}),
 'dentin-sensitivity':r(['tooth'],'sensitivity',[['冷热敏感'],['刺激去除即缓解']],{exclude:['持续冷热痛','自发痛','夜间痛']}),
 'periodontitis-pattern':r(['tooth','jaw'],'gum',[['牙齿松动','牙龈退缩'],['牙龈出血','牙龈肿胀','口腔异味']],{priority:3}),
 'allergic-rhinitis':r(['nose'],'nasal',[['清水鼻涕','喷嚏'],['鼻痒','鼻塞']],{exclude:['发热','脓性鼻涕'],priority:2}),
 'patellofemoral-pain':r(['knee'],'knee-load',[P,['上下楼加重','蹲起加重']],{exclude:['扭伤后','关节卡住']}),
 'pyelonephritis-pattern':r(['abdomen','spine','hip'],'upper-urinary',[['侧腰痛'],['发热','发冷']],{optional:['尿痛','尿频','呕吐'],locations:['flank'],priority:5}),
 'dyspepsia-pattern':r(['abdomen'],'dyspepsia',[['早饱','餐后饱胀'],['进食后加重','恶心','胀痛']],{locations:['epigastric','luq'],exclude:['黑便','呕血','体重下降']}),
 'sleep-deprivation':r(ALL,'lifestyle-sleep',[['睡眠不足','失眠'],['疲劳乏力','白天困倦']],{lifestyle:true}),
 'sitting-posture':r(['neck','spine','shoulder','hip'],'mechanical',[P,['久坐后'],['休息后缓解','活动后缓解']],{lifestyle:true,exclude:['外伤后','扭伤后'],priority:4}),
 'delayed-muscle-soreness':r(limb,'mechanical',[['酸痛','酸胀','紧绷'],['新运动后1至3天']],{tissues:['muscle'],lifestyle:true,priority:5}),
 'standing-fatigue':r(['hip','knee','lower-limb','ankle','foot'],'standing',[['酸痛','酸胀','沉重感'],['久站后'],['休息后缓解']],{exclude:['单侧肿胀'],lifestyle:true}),
 'dehydration-pattern':r(ALL,'hydration',[['口渴口干'],['尿色深','尿量减少']],{optional:['喝水少','呕吐','腹泻'],lifestyle:true}),
 'screen-dry-eye':r(['eye'],'eye-surface',[['眼干','异物感'],['长时间看屏幕']],{exclude:['视物模糊','畏光','外伤后'],lifestyle:true,priority:3}),
 'constipation-pattern':r(['abdomen','pelvis'],'constipation',[['便秘'],['干硬便','排便费力']],{optional:['喝水少','久坐后','腹胀'],exclude:['血便','黑便','呕吐']}),
 'ibs-pattern':r(['abdomen'],'bowel-chronic',[P,['排便后缓解'],['腹泻','便秘','排便改变'],['反复数月']],{exclude:['血便','黑便','发热','体重下降'],priority:3}),
 'costochondritis-pattern':r(['chest'],'chest-wall',[['局部压痛'],['呼吸痛','活动诱发']],{exclude:['外伤后'],optional:['咳嗽']}),
 'blood-test-direction':r(ALL,'blood',[['无故淤青','异常出血'],['疲劳乏力','苍白','反复感染']],{optional:['体重下降','夜间痛'],priority:3}),
 'stress-bone-injury':r(['lower-limb','foot','hip'],'injury',[['反复用力','运动后'],['局部压痛'],['负重加重']],{tissues:['skeleton'],priority:3}),
 'septic-joint-warning':r(joints,'joint',[['红肿','局部肿胀'],['发热','发冷'],['活动受限','无法承重']],{priority:6})
};
export const RULE_PAIN_TAGS=P;
