import {hasReportedPain,LOCAL_PAIN_TAGS} from './symptomLanguage.js';
import {referenceLocation} from './reportLocation.js';
const has=(report,...tags)=>tags.some(tag=>report.tags.has(tag));
const pain=report=>hasReportedPain(report.tags);
const upperAbdominalPain=report=>[...LOCAL_PAIN_TAGS,'向背部放射','进食后腹痛','油腻餐后痛'].some(tag=>report.tags.has(tag));
const jointRegions=['shoulder','upper-limb','hand','hip','knee','ankle','foot'];
const musculoskeletalRegions=['neck','spine','chest','abdomen','pelvis','lower-limb',...jointRegions];

// Source scope and independent positive/negative cases are recorded under the
// related review entries in data/evidence-review-2026-10.json. These predicates
// route assessment; they do not create diagnoses or require missing checkboxes.
const rules=[
 {id:'reported-strength-loss-review',level:'prompt',matches:(p,r)=>has(r,'肌力下降'),
  zh:'已报告力量下降，应尽快检查并核实起病、进展及分布；不能仅以疲劳或局部受压解释。若突然出现或快速加重，立即就医评估。',
  en:'Reported reduced strength needs prompt examination of onset, progression and distribution rather than assuming fatigue or local compression. Sudden onset or rapid worsening needs immediate assessment.'},
 {id:'neck-back-weight-change-review',level:'prompt',matches:(p,r)=>['neck','spine'].includes(p.region)&&pain(r)&&has(r,'体重下降'),
  zh:'已报告颈背痛和无意中体重下降：请尽快就医核实原因，不能仅按姿势问题解释；这些选择不能确定具体疾病。',
  en:'Neck/back pain and unintentional weight loss have been reported. Arrange prompt assessment of the cause rather than assuming posture alone. These selections do not establish a specific disease.'},
 {id:'facial-neuralgic-sensory-review',level:'prompt',matches:(p,r)=>['head','jaw','tooth'].includes(p.region)&&has(r,'电击','刀割感')&&has(r,'触碰诱发')&&has(r,'短暂发作')&&has(r,'感觉减退'),
  zh:'所选头面区域短暂、触碰诱发的电击或刀割样痛伴感觉减退：尽快接受神经专科评估查明原因，不能仅按常见神经痛自行处理；这也不等于排除三叉神经痛。',
  en:'Brief, touch-triggered electric or cutting pain in the selected head/facial area with reduced sensation needs prompt neurological assessment of its cause rather than routine neuralgia self-care. Reduced sensation does not itself rule out trigeminal neuralgia.'},
 {id:'oral-swelling-restricted-opening',level:'emergency',matches:(p,r)=>['tooth','jaw'].includes(p.region)&&has(r,'牙龈肿胀','面部肿胀','流脓')&&has(r,'张口受限'),
  zh:'牙龈/颌面肿胀或流脓伴张口受限：立即急诊评估可能的感染扩散；不要等出现发烧或再按普通颞下颌关节不适处理。',
  en:'Gum/facial swelling or pus with restricted mouth opening needs emergency assessment for possible spreading infection. Do not wait for fever or treat it only as a routine jaw-joint problem.'},
 {id:'dental-infection-review',level:'same-day',matches:(p,r)=>['tooth','jaw'].includes(p.region)&&(has(r,'流脓')||has(r,'牙龈肿胀','面部肿胀')&&has(r,'发热','发冷')||(pain(r)||has(r,'持续冷热痛','自发痛','夜间痛'))&&has(r,'发热','发冷')),
  zh:'牙齿/颌面流脓，或局部不适/肿胀伴发热或寒战：今天尽快联系急诊牙科评估。若张口、吞咽或呼吸受影响，立即急诊。',
  en:'Dental/facial pus, or local discomfort/swelling with fever or chills, needs same-day urgent dental assessment. Difficulty opening the mouth, swallowing or breathing needs emergency care.'},
 {id:'dental-observation-review',level:'prompt',matches:(p,r)=>['tooth','jaw'].includes(p.region)&&has(r,'持续冷热痛','自发痛','夜间痛','牙龋洞','牙齿裂纹'),
  zh:'持续冷热痛、自发/夜间痛或已观察到牙体缺损，应尽快安排牙科检查，不必等超过两天或补足更多勾选。不能据此判断龋深、牙髓状态或是否需要根管治疗。',
  en:'Lingering thermal pain, spontaneous/night pain or an observed tooth defect needs prompt dental examination without waiting two days or adding more checkboxes. These reports do not establish decay depth, pulp status or a need for root-canal treatment.'},
 {id:'eye-injury-warning',level:'emergency',matches:(p,r)=>p.region==='eye'&&has(r,'外伤后')&&(has(r,'眼红','视物模糊','复视','畏光','突发剧痛')),
  zh:'眼部受伤后出现红眼、畏光、剧痛或视觉变化：立即眼科急诊评估，不先按普通眼表刺激或干眼处理。',
  en:'Redness, light sensitivity, severe pain or visual change after eye injury needs emergency eye assessment rather than routine surface-irritation or dry-eye self-care.'},
 {id:'eye-injury-review',level:'same-day',matches:(p,r)=>p.region==='eye'&&has(r,'外伤后')&&(has(r,'异物感','流脓')||pain(r)),
  zh:'眼周受伤后报告不适、异物感或流脓：今天联系眼科评估，不能先按普通干眼处理。若视力改变、畏光、剧痛，脓液来自眼内/眼表，或有物体刺入，立即急诊。',
  en:'Discomfort, a foreign-body sensation or pus reported after injury around the eye needs same-day eye assessment rather than assuming dry eye. Visual change, light sensitivity, severe pain, pus from the eye itself or a penetrating object needs emergency care.'},
 {id:'red-eye-visual-warning',level:'emergency',matches:(p,r)=>p.region==='eye'&&has(r,'眼红')&&has(r,'视物模糊','复视','畏光'),
  zh:'红眼伴视觉变化或畏光：立即眼科急诊评估，不等待自行缓解。',
  en:'A red eye with visual change or light sensitivity needs emergency eye assessment rather than waiting for it to settle.'},
 {id:'diplopia-after-injury',level:'emergency',matches:(p,r)=>has(r,'复视')&&has(r,'外伤后'),
  zh:'受伤后出现复视：立即急诊评估，不等待其他症状。',
  en:'Double vision after injury needs emergency assessment without waiting for additional symptoms.'},
 {id:'sudden-diplopia',level:'same-day',matches:(p,r)=>has(r,'复视')&&has(r,'突然起病'),
  zh:'突然出现复视：今天尽快接受眼科或医疗评估；不能从模型点位判断原因。',
  en:'Sudden double vision needs same-day eye/medical assessment; the selected anatomy cannot establish its cause.'},
 {id:'diplopia-review',level:'prompt',matches:(p,r)=>has(r,'复视'),
  zh:'复视即使时有时无，也应安排眼科或医疗检查；不能仅按眼干或视觉疲劳解释。',
  en:'Double vision needs an eye or medical examination even if intermittent; do not assume dry eye or visual fatigue.'},
 {id:'sudden-hearing-combination',level:'same-day',matches:(p,r)=>has(r,'听力下降')&&has(r,'突然起病'),
  zh:'听力突然下降：今天立即联系耳鼻喉科或急诊评估，不因同时耳痛、像耳垢或耳炎而等待。当前选择不能区分听力损失类型。',
  en:'Sudden hearing reduction needs same-day urgent ENT or emergency assessment. Do not wait because there is also ear pain or a possible wax/infection explanation; these selections cannot identify the hearing-loss type.'},
 {id:'purulent-drainage-review',level:'prompt',matches:(p,r)=>!['tooth','jaw'].includes(p.region)&&has(r,'流脓'),
  zh:'已报告局部流脓，应尽快就医检查感染来源；不能按单纯皮肤刺激或骨肌劳损解释，模型也不能判断感染深度。',
  en:'Reported pus needs prompt assessment of a possible infection source. Do not explain it solely as skin irritation or musculoskeletal strain; the model cannot determine infection depth.'},
 {id:'skin-change-systemic-warning',level:'same-day',matches:(p,r)=>has(r,'皮疹','红斑','红肿','局部肿胀','流脓')&&has(r,'发热','发冷'),
  zh:'皮疹、红肿/肿胀或流脓伴发热或寒战：当天尽快就医检查是否感染等原因，不能只按接触刺激护理。',
  en:'Rash, redness/swelling or pus with fever or chills needs same-day assessment for infection and other causes rather than contact-irritation care alone.'},
 {id:'nosebleed-duration-review',level:'same-day',matches:(p,r)=>p.region==='nose'&&has(r,'鼻出血')&&has(r,'持续数小时','持续1至3天','持续超过3天','持续超过10天'),
  zh:'鼻出血伴较长病程，应当天联系医生核实是否反复或未止。若现在仍出血且正确持续按压鼻软部10–15分钟未止，立即急诊；不要把病程直接当成已持续大量出血。',
  en:'Nosebleeding with a longer reported course needs same-day advice to clarify whether it is recurrent or ongoing. Bleeding that continues despite 10–15 minutes of firm pressure on the soft nose needs emergency care. Duration alone does not establish continuous heavy bleeding.'},
 {id:'reported-haematemesis',level:'emergency',matches:(p,r)=>has(r,'呕血'),
  zh:'报告呕血时应立即联系医疗机构评估；如仍在出血，或伴晕厥、冷汗、气短、腹痛或黑便，立即急诊。未勾伴随表现不能证明出血已停或情况稳定。',
  en:'Vomiting blood needs immediate medical assessment. Ongoing bleeding, fainting, cold sweat, breathlessness, abdominal pain or black stools needs emergency care. Unreported associated symptoms do not establish that bleeding has stopped or that you are stable.'},
 {id:'upper-left-trauma',level:'same-day',matches:(p,r)=>p.region==='abdomen'&&referenceLocation(p,r)==='luq'&&has(r,'外伤后')&&upperAbdominalPain(r),
  zh:'左上腹/脾区受伤后出现疼痛或压痛：今天尽快到医疗机构评估内脏损伤，不能只按表面挫伤处理；部分问题可延迟出现。',
  en:'Pain or tenderness after injury in the left upper abdominal/splenic area needs same-day assessment for internal injury. Do not assume a surface bruise; some problems can appear later.'},
 {id:'upper-left-trauma-shoulder-warning',level:'emergency',matches:(p,r)=>p.region==='abdomen'&&referenceLocation(p,r)==='luq'&&has(r,'外伤后')&&has(r,'肩尖痛','晕厥','突发剧痛'),
  zh:'左上腹/脾区受伤后伴肩尖痛、晕厥或突发剧痛：立即急诊评估可能的内脏损伤，不等待其他表现。',
  en:'Shoulder-tip pain, fainting or sudden severe pain after injury in the left upper abdominal/splenic area needs emergency assessment for possible internal injury without waiting for other signs.'},
 {id:'renal-colic-fever',level:'emergency',matches:(p,r)=>['abdomen','spine','hip'].includes(p.region)&&has(r,'发热','发冷')&&(has(r,'腰腹向腹股沟放射')||has(r,'绞痛')&&referenceLocation(p,r)==='flank'),
  zh:'侧腰绞痛或腰腹向腹股沟放射，并伴发热/寒战：立即就医评估感染或排尿通路受阻等原因，不需等出现血尿。不能凭选择确诊结石。',
  en:'Flank colic or pain radiating toward the groin with fever or chills needs immediate assessment for infection or urinary obstruction. Do not wait for blood in urine; these selections do not diagnose a stone.'},
 {id:'right-upper-pain-fever',level:'same-day',matches:(p,r)=>p.region==='abdomen'&&referenceLocation(p,r)==='ruq'&&upperAbdominalPain(r)&&has(r,'发热','发冷'),
  zh:'右上腹/肝胆区域疼痛伴发热或寒战：当天尽快就医检查，不需要等油腻餐后发作或出现黄疸才评估。',
  en:'Right upper abdominal/liver-biliary area pain with fever or chills needs same-day assessment. Do not wait for fatty-meal association or jaundice.'},
 {id:'right-upper-pain-fever-jaundice',level:'emergency',matches:(p,r)=>p.region==='abdomen'&&referenceLocation(p,r)==='ruq'&&upperAbdominalPain(r)&&has(r,'发热','发冷')&&has(r,'黄疸'),
  zh:'右上腹疼痛、发热/寒战和黄疸同时出现：立即急诊检查胆道感染或阻塞等原因，不能只按普通胆绞痛观察。',
  en:'Right upper abdominal pain together with fever/chills and jaundice needs emergency assessment for biliary infection or obstruction rather than observation as ordinary biliary colic.'},
 {id:'upper-abdominal-pain-vomiting',level:'same-day',matches:(p,r)=>p.region==='abdomen'&&['epigastric','luq'].includes(referenceLocation(p,r))&&upperAbdominalPain(r)&&has(r,'呕吐')&&has(r,'持续加重','向背部放射'),
  zh:'上腹或左上腹疼痛伴呕吐，且持续加重或向背部放射：当天尽快就医检查；未报告背部放射不能作为继续观察的理由。',
  en:'Upper or left upper abdominal pain with vomiting and worsening or back radiation needs same-day assessment. Lack of reported back radiation is not a reason to keep observing worsening symptoms.'},
 {id:'constipation-alarm-features',level:'same-day',matches:(p,r)=>['abdomen','pelvis'].includes(p.region)&&has(r,'便秘')&&has(r,'发热','发冷','呕吐'),
  zh:'便秘同时伴发热、寒战或呕吐：当天尽快就医检查，先不要仅靠增加纤维或自行观察处理。',
  en:'Constipation with fever, chills or vomiting needs same-day assessment before relying only on extra fibre or observation.'},
 {id:'epigastric-pressure-cold-sweat',level:'same-day',matches:(p,r)=>p.region==='abdomen'&&referenceLocation(p,r)==='epigastric'&&has(r,'压迫感')&&has(r,'冷汗'),
  zh:'上腹压迫感伴冷汗：当天立即联系医疗机构评估，不能仅按胃部问题解释；需考虑包括心脏在内的其他原因。',
  en:'Upper abdominal pressure with cold sweat needs same-day medical assessment. Do not attribute it solely to the stomach; cardiac and other causes need consideration.'},
 {id:'acute-epigastric-pressure-cold-sweat',level:'emergency',matches:(p,r)=>p.region==='abdomen'&&referenceLocation(p,r)==='epigastric'&&has(r,'压迫感')&&has(r,'冷汗')&&has(r,'突然起病','持续数小时','持续1至3天','持续超过3天','持续加重'),
  zh:'突然或持续的上腹压迫感伴冷汗：立即急诊评估。上腹不适也可能是心脏警讯，不能先用胃病解释排除。',
  en:'Sudden or ongoing upper abdominal pressure with cold sweat needs emergency assessment. Upper abdominal discomfort can be a cardiac warning and cannot be excluded by a stomach explanation.'},
 {id:'hot-swollen-joint',level:'same-day',matches:(p,r)=>jointRegions.includes(p.region)&&has(r,'红肿','局部肿胀')&&has(r,'局部发热','流脓'),
  zh:'局部肿胀或发红伴热感或流脓：当天尽快就医评估关节及周围组织，不能仅按痛风或滑囊劳损处理；未报告发烧也不能排除感染。',
  en:'Swelling or redness with local heat or purulent drainage needs same-day assessment of the joint and nearby tissues. Do not assume gout or bursal strain; unreported fever does not rule out infection.'},
 {id:'headache-systemic-progressive',level:'same-day',matches:(p,r)=>p.region==='head'&&pain(r)&&has(r,'发热','发冷','持续加重'),
  zh:'头部疼痛伴发热、寒战或持续加重：当天尽快就医评估，不先按普通紧张或偏头痛自行处理。',
  en:'Head pain with fever, chills or progressive worsening needs same-day assessment before routine tension-type or migraine self-care.'},
 {id:'headache-neurological-change',level:'same-day',matches:(p,r)=>p.region==='head'&&pain(r)&&has(r,'复视','肌力下降'),
  zh:'头部疼痛伴复视或力量下降：当天尽快接受神经系统评估；不能把未核实的神经变化当作普通先兆。',
  en:'Head pain with double vision or reduced strength needs same-day neurological assessment; do not assume an unassessed neurological change is a routine aura.'},
 {id:'sudden-motor-or-head-neurological-change',level:'emergency',matches:(p,r)=>has(r,'突然起病')&&(has(r,'肌力下降')||p.region==='head'&&pain(r)&&has(r,'复视')),
  zh:'突然出现力量下降，或突然头痛伴复视：立即联系急救或急诊评估，记录起病时间；不要按局部神经受压先观察。',
  en:'Sudden loss of strength, or sudden head pain with double vision, needs emergency assessment. Record onset time rather than observing it as local nerve compression.'},
 {id:'neck-back-pain-fever',level:'same-day',matches:(p,r)=>['neck','spine'].includes(p.region)&&pain(r)&&has(r,'发热','发冷'),
  zh:'颈背疼痛伴发热或寒战：当天尽快就医排查感染等原因，不能只用久坐或肌肉负荷解释。',
  en:'Neck or back pain with fever or chills needs same-day assessment for infection and other causes; posture or muscle load alone is not an adequate explanation.'},
 {id:'exercise-muscle-urine-warning',level:'emergency',matches:(p,r)=>musculoskeletalRegions.includes(p.region)&&pain(r)&&has(r,'运动后','新运动后1至3天')&&has(r,'尿色深')&&has(r,'肌力下降','局部肿胀','持续加重'),
  zh:'运动后局部或肢体疼痛伴尿色变深及力量下降、肿胀或加重：立即就医检查，不能只按延迟性酸痛或缺水处理。尿色深本身不能确定病因。',
  en:'Local or limb pain after exercise with darker urine and reduced strength, swelling or worsening need immediate medical assessment. Do not assume delayed soreness or dehydration; dark urine alone does not establish a cause.'},
 {id:'injury-with-functional-loss',level:'same-day',matches:(p,r)=>[...jointRegions,'lower-limb'].includes(p.region)&&has(r,'外伤后','扭伤后')&&has(r,'无法承重','关节卡住'),
  zh:'受伤或扭伤后不能承重或关节卡住：当天尽快接受损伤评估，不强行活动。仅靠这些选择不能判断是否骨折或是否需要拍片。',
  en:'Inability to bear weight or a locked joint after injury or twisting needs same-day injury assessment. Do not force movement. These selections cannot determine whether a fracture or imaging is present or needed.'}
];
export function literatureWarnings(profiles,reports){
 const warnings=[];
 for(let i=0;i<profiles.length;i++)for(const rule of rules)if(rule.matches(profiles[i],reports[i]))warnings.push({id:rule.id,level:rule.level,zh:rule.zh,en:rule.en});
 return warnings;
}

export const LITERATURE_RULE_IDS=rules.map(rule=>rule.id);
